### ISSUE TITLE
Assertion Failed: calling set on destroyed object when navigating away after save

### ISSUE THREAD

**Issue by alex88** [ivanvanderbyl/ember-spin-button#2]
I've the spin button in my template:

```
= spin-button class='btn btn-success' action='save' inFlight=model.inFlight buttonStyle='zoom-in' | Done
```

this is my action:

```coffeescript
    save: ->
      @get('model').save().then =>
        @transitionToRoute 'dashboard', @get('model')
      return
```

however after navigating away and going back to the page with the button it's empty (no loading spinner and no "Done" text).

Sometimes it also throws an exception on this line https://github.com/ivanvanderbyl/ember-spin-button/blob/master/app/components/spin-button.js#L109 saying:

```
Assertion Failed: calling set on destroyed object
```

is an error in my usage or somewhere else?

**Comment by ivanvanderbyl** [comment]
Sounds like a bug in one of the internals. I've seen this before. What version of ember are you on?

**Comment by alex88** [comment]
Actually on 1.12 but also older versions (1.11).
Anyway, I've seen that changing `inFlight=model.inFlight` to `inFlight=someControllerProperty` and changing that property before `save()` and after `save()` made it working properly

**Comment by ivanvanderbyl** [comment]
This shouldn't be an issue with Ember 1.13+ and promise based actions (see readme)
