### ISSUE TITLE
Error: Cannot find module 'broccoli-funnel'

### ISSUE THREAD

**Issue by AndrewAskins** [ivanvanderbyl/ember-spin-button#3]
Hey just wanted to let you know I ran into this error because I didn't have the broccoli-funnel module installed. It was really simple to fix, just ran

`npm install broccoli-funnel`

and then reran

`ember-cli install ember-spin-button`

Might just be something to add as a dependency, maybe. Thanks for making this though!

**Comment by ivanvanderbyl** [comment]
This is now resolved thanks to #4
