### ISSUE TITLE
How to change the button text colour?

### ISSUE THREAD

**Issue by shopapps** [ivanvanderbyl/ember-spin-button#8]
Hi,
Where i am using a lighter colour for the background of the button the white text is not suitable.  Is there a method to override the text colour as well as the background colour?

**Comment by ivanvanderbyl** [comment]
Hi @shopapps — Just apply your own CSS style to it after including the button styles. Or don't include the button styles and roll it from scratch.

**Comment by shopapps** [comment]
Ok thanks.

To help others here is the CSS I am currently using (i dont know if it is the correct way):

    .spin-button[data-color=white]  {
      color: #212c34;
    }

but perhaps as a future enhancement you could add support either via scss: 

    @include buttonColor( 'white', #e5e5e5 , #000000);

where the first is the background and the second is the text color?  or maybe via another variable when calling the #spin-button eg.

    text-color="black"

**Comment by ivanvanderbyl** [comment]
PRs accepted :)
